server:
  forward-headers-strategy: framework
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/regulatory_db
    username: user
    password: pass
    driverClassName: org.postgresql.Driver
    hikari:
      schema: 'public'
  cache:
    type: simple