spring:
  config:
    import: 'file:users/core/src/main/resources/application.yaml'
  rabbitmq:
    host: 10.206.128.24
    username: users-service
    password: users-service
    virtual-host: /
    port: 5672
    listener:
      type: simple
      simple:
        max-concurrency: 1
        concurrency: 1
        prefetch: 1

services:
  rabbit:
    exchange: TRAFFIC_EXCHANGE
    queue: USERS-QUEUE

