spring:
  config:
    import: 'file:users/core/src/main/resources/application.yaml'
  rabbitmq:
    host: 10.206.128.24
    username: users-service
    password: users-service
    virtual-host: /
    port: 5672
    listener:
      type: simple
      simple:
        max-concurrency: 1
        concurrency: 1
        prefetch: 1

services:
  rabbitmq:
    exchange: BFF_EXCHANGE
    queue: USERS-QUEUE
    routing-keys:
      - users.driver.create
    dlq-queue: USERS-QUEUE-DLQ
    dlq-routing-key: users.driver.dlq

