version: '3.3'

services:
#  pg_price:
#    extends:
#      file: docker-compose.base.yml
#      service: pg_price
#
  pg_tasks:
    container_name: pg_tasks
    extends:
      file: docker-compose.base.yml
      service: pg_tasks
#
#  pg_notification:
#    extends:
#      file: docker-compose.base.yml
#      service: pg_notification
#
#  pg_incidents:
#    extends:
#      file: docker-compose.base.yml
#      service: pg_incidents
#
  pg_users:
    extends:
      file: docker-compose.base.yml
      service: pg_users

  rmq_price:
    extends:
      file: docker-compose.base.yml
      service: rmq_price

#  tasks-core:
#    extends:
#      file: docker-compose.services.yml
#      service: tasks-core

  tasks-api:
    extends:
      file: docker-compose.services.yml
      service: tasks-api

  tasks-watcher:
    extends:
      file: docker-compose.services.yml
      service: tasks-watcher

#  notification:
#    extends:
#      file: docker-compose.services.yml
#      service: notification
#
#  incidents-core:
#    extends:
#      file: docker-compose.services.yml
#      service: incidents-core
#
#  incidents-api:
#    extends:
#      file: docker-compose.services.yml
#      service: incidents-api
#
#  incidents-watcher:
#    extends:
#      file: docker-compose.services.yml
#      service: incidents-watcher
#
#  users-core:
#    extends:
#      file: docker-compose.services.yml
#      service: users-core
#
  users-api:
    extends:
      file: docker-compose.services.yml
      service: users-api

  users-watcher:
    extends:
      file: docker-compose.services.yml
      service: users-watcher
