version: '3.3'
services:
  # ----- БД образ-шаблон -----
  pg_base:
    image: postgres:15
    container_name: pg_base
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass


  rmq_bff:
    image: rabbitmq:3.11.2-management
    container_name: rmq_bff
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
      - RABBITMQ_DEFAULT_VHOST=/
    entrypoint: docker-entrypoint.sh rabbitmq-server
