version: '3.3'
services:
  pg_tasks:
    image: postgis/postgis:15-3.3
    container_name: pg_tasks
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=task
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
    #      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    healthcheck:
      test: "PGPASSWORD=pass pg_isready -h 127.0.0.1 -U user -d path_price"

#  keycloak:
#    image: bitnami/keycloak:21.1.2
#    container_name: 'keycloak'
#    depends_on:
#      - postgres
#    volumes:
#      - ./volumes/cacerts:/opt/bitnami/keycloak/certs-spi/cacerts
#      - ./volumes/keycloak:/opt/bitnami/keycloak
#    env_file:
#      - .env
#    ports:
#      - "8080:8443"
#    restart: always
#    networks:
#      lan:
#        ipv4_address: 172.26.0.11

  driver-bff-api:
    container_name: driver-bff-api
    restart: on-failure
    ports:
      - '8080:8080'
    image: dellinii/driver-bff
    environment:
      - SPRING_CONFIG_LOCATION=/app/application.yml
    entrypoint:
      - java
      - -XX:InitialRAMPercentage=75
      - -XX:MaxRAMPercentage=75
      - -Xss256k
      - -Dconfig.override_with_env_vars=true
      - -Djava.security.egd=file:/dev/./urandom
      - -jar
      - /app/driver-bff-api.jar

  driver-bff-notification:
    container_name: driver-bff-notification
    restart: on-failure
    image: dellinii/driver-bff
    environment:
      - SPRING_CONFIG_LOCATION=/app/application.yml
    entrypoint:
      - java
      - -XX:InitialRAMPercentage=75
      - -XX:MaxRAMPercentage=75
      - -Xss256k
      - -Dconfig.override_with_env_vars=true
      - -Djava.security.egd=file:/dev/./urandom
      - -jar
      - /app/driver-bff-notification.jar

  driver-bff-adapter:
    container_name: driver-bff-adapter
    restart: on-failure
    image: dellinii/driver-bff
    environment:
      - SPRING_CONFIG_LOCATION=/app/application.yml
    entrypoint:
      - java
      - -XX:InitialRAMPercentage=75
      - -XX:MaxRAMPercentage=75
      - -Xss256k
      - -Dconfig.override_with_env_vars=true
      - -Djava.security.egd=file:/dev/./urandom
      - -jar
      - /app/driver-bff-adapter.jar
