management:
  endpoint:
    health:
      probes:
        enabled: true
    mappings:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'health,mappings'
  server:
    port: 8081

services:
  rabbitmq:
    exchange: BFF_EXCHANGE
    routing-key:
      user: users.driver.create

