server:
  forward-headers-strategy: framework
  port: 8080

spring:
  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog.xml'
    default-schema: 'public'
  datasource:
    url: jdbc:postgresql://localhost:5438/chat_db
    username: user
    password: pass
    driverClassName: org.postgresql.Driver
    hikari:
      schema: 'public'
      autocommit: false
  cache:
    type: simple
